# Generated by Django 3.1.6 on 2021-02-08 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kunde',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('vorname', models.CharField(blank=True, max_length=300, null=True)),
                ('strasse', models.CharField(blank=True, max_length=300, null=True)),
                ('hausnummer', models.CharField(blank=True, max_length=300, null=True)),
                ('plz', models.CharField(blank=True, max_length=300, null=True)),
                ('ort', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Auftrag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.CharField(blank=True, choices=[('Dienstleistung', 'Dienstleistung'), ('Produkt', 'Produkt')], max_length=300, null=True)),
                ('beschreibung', models.CharField(blank=True, max_length=300, null=True)),
                ('preis', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('status', models.CharField(blank=True, choices=[('Offen', 'Offen'), ('Bezahlt', 'Bezahlt')], max_length=300, null=True)),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('kunde', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.kunde')),
            ],
        ),
    ]
