# Generated by Django 3.1.4 on 2021-02-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auftrag',
            name='datum',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
