# Generated by Django 3.1.4 on 2021-02-10 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20210208_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ausgangsrechnung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.CharField(blank=True, choices=[('Dienstleistung', 'Dienstleistung'), ('Produkt', 'Produkt')], max_length=300, null=True)),
                ('beschreibung', models.CharField(blank=True, max_length=300, null=True)),
                ('preis', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('status', models.CharField(blank=True, choices=[('Offen', 'Offen'), ('Bezahlt', 'Bezahlt')], max_length=300, null=True)),
                ('datum', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Kunde',
            new_name='Debitor',
        ),
        migrations.DeleteModel(
            name='Auftrag',
        ),
        migrations.AddField(
            model_name='ausgangsrechnung',
            name='debitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.debitor'),
        ),
    ]
