# Generated by Django 3.1.4 on 2021-02-10 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20210210_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kreditor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma', models.CharField(blank=True, max_length=300, null=True)),
                ('strasse', models.CharField(blank=True, max_length=300, null=True)),
                ('hausnummer', models.CharField(blank=True, max_length=300, null=True)),
                ('plz', models.CharField(blank=True, max_length=300, null=True)),
                ('ort', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Eingangsrechnung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.CharField(blank=True, choices=[('Dienstleistung', 'Dienstleistung'), ('Produkt', 'Produkt')], max_length=300, null=True)),
                ('beschreibung', models.CharField(blank=True, max_length=300, null=True)),
                ('preis', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('status', models.CharField(blank=True, choices=[('Offen', 'Offen'), ('Bezahlt', 'Bezahlt')], max_length=300, null=True)),
                ('datum', models.DateTimeField(blank=True, null=True)),
                ('kreditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.kreditor')),
            ],
        ),
    ]
